package model.team;

public enum Channels {
	NEW_SEARCH_EVENT,
	TERMINATE_SEARCH_EVENT,
	AUDIO_PS_MM_COMM,
	AUDIO_MM_PS_COMM,
	NEW_SEARCH_AREA_EVENT,
	TARGET_DESCRIPTION_EVENT,
	AUDIO_VO_MM_COMM,
	AUDIO_MM_VO_COMM,
	VIDEO_MM_VGUI_COMM,
	AUDIO_OP_MM_COMM,
	AUDIO_MM_OP_COMM,
	VIDEO_VGUI_MM_COMM,
	AUDIO_VGUI_MM_COMM,
	VIDEO_OGUI_OP_COMM,
	DATA_OP_OGUI_COMM,
	AUDIO_VO_OP_COMM, DATA_VO_VGUI, DATA_OP_UAV, DATA_MM_VGUI_COMM, VIDEO_UAV_OP_COMM, DATA_UAV_VGUI_COMM, DATA_UAV_OGUI_COMM, VIDEO_OP_OGUI_COMM, NEW_TARGET_DESCRIPTION_EVENT, DATA_UAV_COMM, DATA_UAV_UAV_COMM, HAG_EVENT, CRASHED_EVENT, DATA_OP_UAV_COMM, DATA_OGUI_UAV_COMM,
	
	
//	NEW_SEARCH_EVENT(Type.AUDIO),
//	TERMINATE_SEARCH_EVENT(Type.AUDIO),
//	
//	PS_MM_COMM(Type.AUDIO),
//	
//	MM_PS_COMM(Type.AUDIO)
//	;
//	
//	private Type _type;
//	
//	private Channels(Type type)
//	{
//		this._type = type;
//	}
//	
//	public Type type()
//	{
//		return _type;
//	}
	
}
